# Generated by Django 6.0.4 on 2026-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='entreprise',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='stage',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='type_stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Candidature',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
