# Generated by Django 6.0.4 on 2026-04-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='entreprise',
            new_name='localisation',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='stage',
            name='est_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='pre_embauche',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type_stage',
            field=models.CharField(choices=[('PFE', 'PFE'), ('ETE', 'ETE')], max_length=10),
        ),
    ]
