# Generated by Django 6.0.4 on 2026-04-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_rename_entreprise_stage_localisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
